### ISSUE TITLE
Add microsite

### ISSUE THREAD

**Issue by nashid** [DanielaSfregola/twitter4s#231] opened 2018-10-23 23:05 UTC
I think adding this would be cool

https://47deg.github.io/sbt-microsites/

**Comment by nashid** [comment] 2018-10-23 23:06
I can work on it 👍

**Comment by DanielaSfregola** [comment] 2018-10-23 23:13
Thanks @nashid. 
(issue is potentially a duplicate of #173)

**Comment by DanielaSfregola** [comment] 2019-03-15 17:53
Closing this as duplicate of #173

**Closed by DanielaSfregola** 2019-03-15 17:53 UTC
